export const EnaAppData = [
  {
    vegName: 'Avokado',
    engVegName: 'Avocado',
    category: 'Fruit',
    price: 35.2,
    priceWithTax: 36.96,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://5.imimg.com/data5/QH/NP/MY-27346073/fresh-avocado-500x500.jpg',
  },
  {
    vegName: 'Baby špinat 100g',
    engVegName: 'Baby spinach',
    category: 'Vegetable',
    price: undefined,
    priceWithTax: 0,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://woolly.io/wp-content/uploads/2022/07/baby-spinach-1.png',
  },
  {
    vegName: 'Banana',
    engVegName: 'Banana',
    category: 'Fruit',
    price: 9.9,
    priceWithTax: 10.4,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://vitamedica.com/wellness-blog/wp-content/uploads/2011/02/Cauliflower.jpg',
  },
  {
    vegName: 'Celer korjen',
    engVegName: 'Celer korjen',
    category: 'Vegetable',
    price: 8,
    priceWithTax: 8.4,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://cdn.shopify.com/s/files/1/0256/6540/4982/products/CLER_KORJEN_300x300.jpg?v=1579100746',
  },
  {
    vegName: 'Celer list',
    engVegName: 'Celeriac',
    category: 'Vegetable',
    price: 14.5,
    priceWithTax: 15.23,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://cdn-efcpg.nitrocdn.com/aDVYwsugCEsVzcQMEKFESHmZMgcKZcvE/assets/static/optimized/rev-2a1b5d4/wp-content/uploads/2022/04/how-to-cook-celeriac.jpg',
  },
  {
    vegName: 'Kesten',
    engVegName: 'Chestnut',
    category: 'Dryfruit',
    price: 40,
    priceWithTax: 42,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://m.media-amazon.com/images/I/41oN7eDnWcL._AC_.jpg',
  },
  {
    vegName: 'Cikorija',
    engVegName: 'Chicory',
    category: 'Vegetable',
    price: 35,
    priceWithTax: 36.75,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://res.cloudinary.com/dk0z4ums3/image/upload/v1639449834/attached_image_th/bluechicoryflowerandabowlofinstantchicorypowder.jpg',
  },
  {
    vegName: 'chili mix (trenutno nedostupno)',
    engVegName: 'chili mix',
    category: 'Spices',
    price: 10,
    priceWithTax: 10.5,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://img1.exportersindia.com/product_images/bc-full/2019/4/6192300/dried-red-chili-powder-1554713075-4840124.png',
  },
  {
    vegName: 'Kineski kupus',
    engVegName: 'Chinese cabbage',
    category: 'Vegetable',
    price: 13,
    priceWithTax: 13.65,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://www.bazaarfresh.in/wp-content/uploads/2018/10/chinesecabbage.jpg',
  },
  {
    vegName: 'Grah šareni / trešnjevac',
    engVegName: 'Cranberry bean',
    category: 'Pulses',
    price: 17,
    priceWithTax: 17.85,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://thumbs.dreamstime.com/b/borlotti-beans-also-know-as-cranberry-roman-romano-isolated-white-background-58396570.jpg',
  },
  {
    vegName: 'Cvijet tikvice ( 8 komada )',
    engVegName: 'Cvijet tikvice',
    category: 'Vegetable',
    price: 21.75,
    priceWithTax: 22.84,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk_w_7dC-ve7-z94fuf9JALttZhowNUap8WA&usqp=CAU',
  },
  {
    vegName: 'Datulja svježa',
    engVegName: 'Dates',
    category: 'Dryfruit',
    price: 47.25,
    priceWithTax: 49.61,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/02/dates-resized-14ee31f.jpg',
  },
  {
    vegName: 'Datulja kraljevska',
    engVegName: 'Datulja',
    category: 'Dryfruit',
    price: 135,
    priceWithTax: 141.75,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://cdn.shopify.com/s/files/1/0784/3297/products/sacreddatura_39d63b84-c093-41f5-9619-fd218f3229e7_1024x1024.jpeg?v=1457029872',
  },
  {
    vegName: 'Dragon Fruit',
    engVegName: 'Dragon Fruit',
    category: 'Fruit',
    price: 480,
    priceWithTax: 504,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://www.bigbasket.com/media/uploads/p/xxl/40008982_15-fresho-dragon-fruit.jpg',
  },
  {
    vegName: 'Češnjak',
    engVegName: 'Garlic',
    category: 'Vegetable',
    price: 23,
    priceWithTax: 24.15,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2021/05/25/head-of-garlic-and-garlic-cloves.jpg.rend.hgtvcom.406.305.suffix/1621974634336.jpeg',
  },
  {
    vegName: 'Đumbir',
    engVegName: 'Ginger',
    category: 'Spices',
    price: 20,
    priceWithTax: 25,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://www.fitness19.com/wp-content/uploads/2014/01/photodune-1826593-ginger-xs-533x330.jpg',
  },
  {
    vegName: 'Grejp',
    engVegName: 'Grapefruit',
    category: 'Fruit',
    price: 11.42,
    priceWithTax: 11.99,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://media.istockphoto.com/photos/ripe-grapefruit-citrus-fruit-with-half-isolated-on-white-picture-id513123074?k=20&m=513123074&s=612x612&w=0&h=sEd-39dDVq0Ajg9mJ3KzGCBXCa3eh3cj2nKcoX5DGJ8=',
  },
  {
    vegName: 'Grožđe bijelo',
    engVegName: 'Grapes',
    category: 'Fruit',
    price: 10,
    priceWithTax: 10.5,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://www.bigbasket.com/media/uploads/p/xxl/20001427_2-fresho-grapes-green-with-seed.jpg',
  },
  {
    vegName: 'Čičoka',
    engVegName: 'Jerusalem artichoke',
    category: 'Vegetable',
    price: 25.65,
    priceWithTax: 26.93,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEMblk5uxIyhJ76-3cNCMMSyaYxHs6h5-M3012CAiZrPAkVYUkFxCWV92FR7b_4kKh_Uw&usqp=CAU',
  },
  {
    vegName: 'Kivi',
    engVegName: 'Kivi',
    category: 'Fruit',
    price: 19,
    priceWithTax: 19.95,
    unit: 'kg',
    OrderQuantity: 10,
    total: 0,
    img: 'https://thumbs.dreamstime.com/b/kiwi-isolated-white-background-clipping-path-101144959.jpg',
  },
]

export const wareHouse = [
  {
    detail:'Drugs & Pharma',
    image: 'wareHouse1.png',
    bgClass:'bgblue'
  },
  {
    detail:'Building & Construction',
    image: 'wareHouse3.png',
    bgClass:'bgOrange'
  },
  {
    detail:'Drugs & Pharma',
    image: 'wareHouse4.png',
    bgClass:'bgGreen'
  },
  {
    detail:'Drugs & Pharma',
    image: 'wareHouse5.png',
    bgClass:'bgPurple'
  }
]

